### ISSUE TITLE
Replace titles with icons

### ISSUE THREAD

**Issue by NamanArora** [NamanArora/InstaReact#1]
[REACT NATIVE] After logging in, the tab navigator should have the appropriate icons displayed instead of text for navigation.
Simply add new icons and refer them in the tabnav :)

**Comment by ghost** [comment]
I take this one.

**Comment by Shhzdmrz** [comment]
I think this should closed now.

**Comment by ghost** [comment]
@Shhzdmrz 0 courtesy.

**Comment by Shhzdmrz** [comment]
@kytwb Indeed.

**Comment by NamanArora** [comment]
Sorry I left this open. Look out for other upcoming issues from my repos if you're into react native. Thanks guys!
